//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type Trip = $ModelResult<$Schema, "Trip">;
export type Hold = $ModelResult<$Schema, "Hold">;
export type Payment = $ModelResult<$Schema, "Payment">;
export type OrganizationRole = $ModelResult<$Schema, "OrganizationRole">;
export type Member = $ModelResult<$Schema, "Member">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
export type TwoFactor = $ModelResult<$Schema, "TwoFactor">;
export type Post = $ModelResult<$Schema, "Post">;
export type Notification = $ModelResult<$Schema, "Notification">;
export const TripStatus = $schema.enums.TripStatus.values;
export type TripStatus = (typeof TripStatus)[keyof typeof TripStatus];
export const HoldStatus = $schema.enums.HoldStatus.values;
export type HoldStatus = (typeof HoldStatus)[keyof typeof HoldStatus];
export const PaymentStatus = $schema.enums.PaymentStatus.values;
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];
export const PostStatus = $schema.enums.PostStatus.values;
export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];
export const NotificationChannel = $schema.enums.NotificationChannel.values;
export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel];
